insert into students (surname, name, team, major) values ('Шатров','Ярослав','Гамма','НТН');
insert into students (surname, name, team, major) values ('Яцишин','Лев','Йота','НФН');
insert into students (surname, name, team, major) values ('Фонарева','Виктория','Каппа','НТН');
insert into students (surname, name, team, major) values ('Кулаков','Матвей','Омега','НТН');
insert into students (surname, name, team, major) values ('Грошева','Варвара','Альфа','НТН');
insert into students (surname, name, team, major) values ('Савицкий','Кирилл','Гамма','НТН');
insert into students (surname, name, team, major) values ('Бурмистров','Тимофей','Гамма','НТН');
insert into students (surname, name, team, major) values ('Валов ','Денис','Гамма','НОН');
insert into students (surname, name, team, major) values ('Судницина','Анастасия','Пси','НФН');
insert into students (surname, name, team, major) values ('Мулюкина','Анастасия','Пси','НОН');
insert into students (surname, name, team, major) values ('Пономарев','Егор','Лямбда','НТН');
insert into students (surname, name, team, major) values ('Петрова','Виктория','Ипсилон','НТН');
insert into students (surname, name, team, major) values ('Емельянов','Евгений','Бета','НТН');
insert into students (surname, name, team, major) values ('Кирюхин','Евгений','Омега','НОН');
insert into students (surname, name, team, major) values ('Скардин','Лев','Пи','НОН');
insert into students (surname, name, team, major) values ('Кашина','Яна','Пси','НФН');
insert into students (surname, name, team, major) values ('Алибеков','Александр','Эта','НФН');
insert into students (surname, name, team, major) values ('Таюрская','Александра','Мю','НФН');
insert into students (surname, name, team, major) values ('Телегина','Каролина ','Каппа','НФН');
insert into students (surname, name, team, major) values ('Масленникова','Ирина','Мю','НФН');
insert into students (surname, name, team, major) values ('Земскова','Анна','Тета','НФН');
insert into students (surname, name, team, major) values ('Кулешова','Полина','Каппа','НФН');
insert into students (surname, name, team, major) values ('Тучина','Екатерина','Сигма','НФН');
insert into students (surname, name, team, major) values ('Тимофеева','Любовь','Сигма','НФН');
insert into students (surname, name, team, major) values ('Шевелева','Полина','Ню','НФН');
insert into students (surname, name, team, major) values ('Вишневская','Александра','Ро','НОН');
insert into students (surname, name, team, major) values ('Рогожникова','Ксения ','Тета','НЕН');
insert into students (surname, name, team, major) values ('Тетерятникова ','Яна','Кси','НФН');
insert into students (surname, name, team, major) values ('Данилина','Маргарита ','Ню','НФН');
insert into students (surname, name, team, major) values ('Рандина','Светлана ','Тета','НОН');
insert into students (surname, name, team, major) values ('Оюн','Маргарита','Ипсилон','НФН');
insert into students (surname, name, team, major) values ('Лосинская','Софья','Дзета','НЕН');
insert into students (surname, name, team, major) values ('Ганцова','Аделина','Альфа','НФН');
insert into students (surname, name, team, major) values ('Мастихина','Ксения','Дельта','НЕН');
insert into students (surname, name, team, major) values ('Бабкина','Софья','Дзета','НФН');
insert into students (surname, name, team, major) values ('Беккер','Маргарита ','Сигма','НФН');
insert into students (surname, name, team, major) values ('Смирнова','Эва','Тета','НТН');
insert into students (surname, name, team, major) values ('Грозина','Виктория','Тета','НЕН');
insert into students (surname, name, team, major) values ('Зырянова','Елизавета','Пси','НФН');
insert into students (surname, name, team, major) values ('Тарлюк','Екатерина','Ипсилон','НФН');
insert into students (surname, name, team, major) values ('Оюн','Роман ','Тау','НФН');
insert into students (surname, name, team, major) values ('Беккер','Арина','Мю','НТН');
insert into students (surname, name, team, major) values ('Соларева','Полина','Кси','НТН');
insert into students (surname, name, team, major) values ('Шеховцова','Вероника ','Кси','НТН');
insert into students (surname, name, team, major) values ('Грачев','Роман','Эпсилон','НТН');
insert into students (surname, name, team, major) values ('Ганевич','Анна','Альфа','НТН');
insert into students (surname, name, team, major) values ('Капля','Иван','Бета','НТН');
insert into students (surname, name, team, major) values ('Селедкин','Ярослав','Лямбда','НТН');
insert into students (surname, name, team, major) values ('Лысенко','Георгий','Бета','НТН');
insert into students (surname, name, team, major) values ('Коляда','Вадим','Тау','НТН');
insert into students (surname, name, team, major) values ('Серов','Никита','Эта','НТН');
insert into students (surname, name, team, major) values ('Приходько','София ','Ню','НЕН');
insert into students (surname, name, team, major) values ('Тихомирова','Анна','Кси','НЕН');
insert into students (surname, name, team, major) values ('Алешечкин','Михаил','Лямбда','НЕН');
insert into students (surname, name, team, major) values ('Постникова','Алёна ','Дзета','НЕН');
insert into students (surname, name, team, major) values ('Павлюченко','Полина','Ипсилон','НЕН');
insert into students (surname, name, team, major) values ('Козлов','Георгий','Эпсилон','НТН');
insert into students (surname, name, team, major) values ('Россиева','Снежана','Омикрон','НТН');
insert into students (surname, name, team, major) values ('Ченченко','Даниил','Пи','НТН');
insert into students (surname, name, team, major) values ('Трегубович','Андрей ','Эта','НТН');
insert into students (surname, name, team, major) values ('Рябинина','Юлия','Ипсилон','НТН');
insert into students (surname, name, team, major) values ('Глазунов','Никита','Фи','НТН');
insert into students (surname, name, team, major) values ('Панченко','Александр ','Лямбда','НТН');
insert into students (surname, name, team, major) values ('Спичак','Лука','Лямбда','НТН');
insert into students (surname, name, team, major) values ('Панченко','Егор','Бета','НТН');
insert into students (surname, name, team, major) values ('Гуляев','Виктор','Эпсилон','НТН');
insert into students (surname, name, team, major) values ('Трегубович','Максим','Бета','НТН');
insert into students (surname, name, team, major) values ('Абрамов','Александр','Йота','НТН');
insert into students (surname, name, team, major) values ('Ковалева','Юлия','Дзета','НФН');
insert into students (surname, name, team, major) values ('Сюсина ','Светлана','Пси','НФН');
insert into students (surname, name, team, major) values ('Бушина','Надежда ','Альфа','НФН');
insert into students (surname, name, team, major) values ('Глушков','Артём ','Лямбда','НТН');
insert into students (surname, name, team, major) values ('Сафина','Яна','Тета','НТН');
insert into students (surname, name, team, major) values ('Скоробогатько','Елизавета','Кси','НЕН');
insert into students (surname, name, team, major) values ('Казаринова','Мария ','Хи','НТН');
insert into students (surname, name, team, major) values ('Челышкина','Анастасия','Сигма','НТН');
insert into students (surname, name, team, major) values ('Берсенев','Степан ','Эта','НТН');
insert into students (surname, name, team, major) values ('Федоров ','Владимир ','Эта','НТН');
insert into students (surname, name, team, major) values ('Хмельницкая','Марина','Альфа','НТН');
insert into students (surname, name, team, major) values ('Клементьев','Егор','Омега','НТН');
insert into students (surname, name, team, major) values ('Собачкина','Анастасия','Хи','НТН');
insert into students (surname, name, team, major) values ('Петрухина','Светлана','Ню','НТН');
insert into students (surname, name, team, major) values ('Дюбанов','Артур','Фи','НТН');
insert into students (surname, name, team, major) values ('Касьяновский','Максим','Омега','НТН');
insert into students (surname, name, team, major) values ('Чичкова','Антонина ','Дельта','НТН');
insert into students (surname, name, team, major) values ('Карабеков','Мухаммадияр','Омега','НТН');
insert into students (surname, name, team, major) values ('Блинов','Артемий','Йота','НТН');
insert into students (surname, name, team, major) values ('Носков','Владимир','Йота','НТН');
insert into students (surname, name, team, major) values ('Попович','Анастасия ','Ню','НТН');
insert into students (surname, name, team, major) values ('Кузнецов','Максим','Тау','НТН');
insert into students (surname, name, team, major) values ('Злобин','Герман','Эта','НТН');
insert into students (surname, name, team, major) values ('Боков','Никита','Йота','НТН');
insert into students (surname, name, team, major) values ('Напрюшкин','Иван','Тау','НТН');
insert into students (surname, name, team, major) values ('Павловский','Андрей','Омега','НЕН');
insert into students (surname, name, team, major) values ('Бельченко','Александр ','Фи','НЕН');
insert into students (surname, name, team, major) values ('Парфенова','Александра','Ипсилон','НЕН');
insert into students (surname, name, team, major) values ('Полина','Мария','Дзета','НЕН');
insert into students (surname, name, team, major) values ('Лебедева','Марина ','Дельта','НЕН');
insert into students (surname, name, team, major) values ('Павловская','Диана','Альфа','НЕН');
insert into students (surname, name, team, major) values ('Панченко','Екатерина ','Ню','НЕН');
insert into students (surname, name, team, major) values ('Андриянов','Евгений','Йота','НЕН');
insert into students (surname, name, team, major) values ('Гутова','Дарья','Дельта','НЕН');
insert into students (surname, name, team, major) values ('Мансурова','Дарья ','Ипсилон','НЕН');
insert into students (surname, name, team, major) values ('Скибина','Ирина','Каппа','nan');
insert into students (surname, name, team, major) values ('Бухаров','Александр','Бета','НФН');
insert into students (surname, name, team, major) values ('Чащина','Ирина','Хи','НОН');
insert into students (surname, name, team, major) values ('Мягкова','Кира','Ипсилон','НОН');
insert into students (surname, name, team, major) values ('Кондрашов','Юрий','Йота','НОН');
insert into students (surname, name, team, major) values ('Емельянова','Дарья ','Ро','НОН');
insert into students (surname, name, team, major) values ('Новикова','Ксения ','Каппа','НОН');
insert into students (surname, name, team, major) values ('Толомеев','Арсений','Пи','НОН');
insert into students (surname, name, team, major) values ('Шадрина','Полина','Пси','НОН');
insert into students (surname, name, team, major) values ('Леонтьев','Георгий','Тау','НФН');
insert into students (surname, name, team, major) values ('Кузярин','Григорий','Фи','НТН');
insert into students (surname, name, team, major) values ('Лебедева','Варвара ','Альфа','НФН');
insert into students (surname, name, team, major) values ('Азаренко ','Богдан ','Пи','НФН');
insert into students (surname, name, team, major) values ('Иванова','Екатерина','Дзета','НТН');
insert into students (surname, name, team, major) values ('Гайнутдинов','Камиль ','Пи','НТН');
insert into students (surname, name, team, major) values ('Дроздова','Мария','Ро','НТН');
insert into students (surname, name, team, major) values ('Сигов','Лев','Эта','НТН');
insert into students (surname, name, team, major) values ('Доманов','Илья ','Эпсилон','НТН');
insert into students (surname, name, team, major) values ('Еремеева','Мария ','Ро','НТН');
insert into students (surname, name, team, major) values ('Смирнова','Полина ','Ро','НТН');
insert into students (surname, name, team, major) values ('Рябинина ','Ольга','Дзета','НТН');
insert into students (surname, name, team, major) values ('Леонтьев','Дмитрий ','Фи','НТН');
insert into students (surname, name, team, major) values ('Баяндин','Руслан','Тау','НТН');
insert into students (surname, name, team, major) values ('Юдин','Фёдор','Пи','НТН');
insert into students (surname, name, team, major) values ('Назаров','Лев','Бета','НТН');
insert into students (surname, name, team, major) values ('Еловых','Ольга ','Омикрон','НТН');
insert into students (surname, name, team, major) values ('Карлов','Данил','Лямбда','НТН');
insert into students (surname, name, team, major) values ('Халиповская','София ','Сигма','НТН');
insert into students (surname, name, team, major) values ('Машуков','Михаил','Эпсилон','НТН');
insert into students (surname, name, team, major) values ('Петрова','Вероника','Хи','НОН');
insert into students (surname, name, team, major) values ('Боловленкова','Нелли','Дельта','НФН');
insert into students (surname, name, team, major) values ('Парфенова','Надежда','Ро','НОН');
insert into students (surname, name, team, major) values ('Синицына','Алена','Кси','НТН');
insert into students (surname, name, team, major) values ('Борисов','Иван ','Гамма','НОН');
insert into students (surname, name, team, major) values ('Кузяков','Андрей','Эпсилон','НТН');
insert into students (surname, name, team, major) values ('Сембинова','Алина','Омикрон','НОН');
insert into students (surname, name, team, major) values ('Михайлов ','Михаил ','Бета','НОН');
insert into students (surname, name, team, major) values ('Нефедов','Даниил','Пи','НОН');
insert into students (surname, name, team, major) values ('Найденова','Лика','Дельта','НОН');
insert into students (surname, name, team, major) values ('Добрицкая','Валерия ','Омикрон','НОН');
insert into students (surname, name, team, major) values ('Путинцева','Софья','Тета','НОН');
insert into students (surname, name, team, major) values ('Соколова','Юлия','Хи','НОН');
insert into students (surname, name, team, major) values ('Эльзезер','Кира','Кси','НОН');
insert into students (surname, name, team, major) values ('Осипкина','Татьяна','Ню','НОН');
insert into students (surname, name, team, major) values ('Левицкий','Артём ','Тау','НОН');
insert into students (surname, name, team, major) values ('Колягина','Юлия ','Омикрон','НОН');
insert into students (surname, name, team, major) values ('Рахимов','Николай','Бета','НОН');
insert into students (surname, name, team, major) values ('Бояндина','Анна ','Ню','НЕН');
insert into students (surname, name, team, major) values ('Серебрякова','Алина','Тета','НЕН');
insert into students (surname, name, team, major) values ('Карпушкина','Софья ','Пси','НЕН');
insert into students (surname, name, team, major) values ('Рябушкина','Арина ','Тета','НЕН');
insert into students (surname, name, team, major) values ('Чабусова','Ульяна','Сигма','НФН');
insert into students (surname, name, team, major) values ('Белешникова','Анна','Мю','НФН');
insert into students (surname, name, team, major) values ('Копылов','Егор','Тау','НТН');
insert into students (surname, name, team, major) values ('Силаева','Алиса','Альфа','НФН');
insert into students (surname, name, team, major) values ('Хархутина','Варвара','Каппа','НФН');
insert into students (surname, name, team, major) values ('Нерушкина','Виктория','Дельта','НФН');
insert into students (surname, name, team, major) values ('Мичикова','Екатерина','Мю','НФН');
insert into students (surname, name, team, major) values ('Варфоломеев','Максим ','Эта','НОН');
insert into students (surname, name, team, major) values ('Калинина','Елизавета','Хи','НЕН');
insert into students (surname, name, team, major) values ('Шадрина','Софья','Пси','НЕН');
insert into students (surname, name, team, major) values ('Виденкина','Алиса','Мю','НЕН');
insert into students (surname, name, team, major) values ('Пущенко','Анастасия','Сигма','НЕН');
insert into students (surname, name, team, major) values ('Гергерт','Эвелина','Альфа','НОН');
insert into students (surname, name, team, major) values ('Шевцова','Виктория','Ню','НОН');
insert into students (surname, name, team, major) values ('Пахомов','Денис','Фи','НТН');
insert into students (surname, name, team, major) values ('Радченко','Аркадий','Гамма','НТН');
insert into students (surname, name, team, major) values ('Савельев','Александр','Гамма','НТН');
insert into students (surname, name, team, major) values ('Жуковская','Алёна','Хи','НТН');
insert into students (surname, name, team, major) values ('Исаев','Михаил','Омега','НТН');
insert into students (surname, name, team, major) values ('Шатохин','Данил','Эпсилон','НТН');
insert into students (surname, name, team, major) values ('Сало','Кирилл','Лямбда','НТН');
insert into students (surname, name, team, major) values ('Якименко','Татьяна','Кси','НЕН');
insert into students (surname, name, team, major) values ('Крикунова','Анастасия ','Омикрон','НЕН');
insert into students (surname, name, team, major) values ('Макарова','Александра','Мю','НЕН');
insert into students (surname, name, team, major) values ('Фалейчик','Софья ','Каппа','НЕН');
insert into students (surname, name, team, major) values ('Дудченко','Алёна','Мю','НЕН');
insert into students (surname, name, team, major) values ('Дисяк','Полина ','Ро','НФН');
insert into students (surname, name, team, major) values ('Новосёлова','Дарья ','Ро','НФН');
insert into students (surname, name, team, major) values ('Степанова','Анна','Кси','НТН');
insert into students (surname, name, team, major) values ('Новашев','Артём','Йота','НТН');
insert into students (surname, name, team, major) values ('Король','Лада','Омикрон','НФН');
insert into students (surname, name, team, major) values ('Трайковская','Алекса','Сигма','НЕН');
insert into students (surname, name, team, major) values ('Дергач','Дарья ','Омикрон','НОН');
insert into students (surname, name, team, major) values ('Курбанова','Марина','Дельта','НОН');
insert into students (surname, name, team, major) values ('Максимов','Константин ','Гамма','НОН');
insert into students (surname, name, team, major) values ('Невежина','Мария','Ипсилон','НФН');
insert into students (surname, name, team, major) values ('Зуева','Арианна','Каппа','НОН');
insert into students (surname, name, team, major) values ('Аршукова','София','Мю','НОН');
insert into students (surname, name, team, major) values ('Король ','Валерия','Пси','НФН');
insert into students (surname, name, team, major) values ('Изаков','Матвей','Эпсилон','НОН');
insert into students (surname, name, team, major) values ('Еремина','Дарья','Омикрон','НФН');
insert into students (surname, name, team, major) values ('Ермолаева','Екатерина','Ро','НФН');
insert into students (surname, name, team, major) values ('Щербакова','Анна','Сигма','НОН');
insert into students (surname, name, team, major) values ('Шевченко','Леонид ','Фи','НОН');
insert into students (surname, name, team, major) values ('Зиборова','Мария','Дзета','НОН');
insert into students (surname, name, team, major) values ('Серостанова','Дарья ','Дзета','НОН');
insert into students (surname, name, team, major) values ('Киселева','Анастасия','Пси','НОН');
insert into students (surname, name, team, major) values ('Куприянова','Полина','Дельта','НОН');
insert into students (surname, name, team, major) values ('Комиссарова','Полина','Каппа','НОН');
insert into students_score (student_id, NTN_score, NEN_score, NON_score, NFN_score) values (1.0,1.0,0.0,0.0,0.0);
insert into students_score (student_id, NTN_score, NEN_score, NON_score, NFN_score) values (2.0,2.0,0.0,5.0,2.0);
insert into students_score (student_id, NTN_score, NEN_score, NON_score, NFN_score) values (3.0,10.0,0.0,2.0,2.0);
insert into students_score (student_id, NTN_score, NEN_score, NON_score, NFN_score) values (4.0,0.0,7.0,4.0,4.0);
insert into students_score (student_id, NTN_score, NEN_score, NON_score, NFN_score) values (5.0,0.0,6.0,0.0,1.0);
insert into students_score (student_id, NTN_score, NEN_score, NON_score, NFN_score) values (6.0,0.0,5.0,7.0,0.0);
insert into students_score (student_id, NTN_score, NEN_score, NON_score, NFN_score) values (7.0,2.0,0.0,3.0,0.0);
insert into students_score (student_id, NTN_score, NEN_score, NON_score, NFN_score) values (8.0,3.0,0.0,0.0,0.0);
insert into students_score (student_id, NTN_score, NEN_score, NON_score, NFN_score) values (9.0,2.0,0.0,3.0,0.0);
insert into students_score (student_id, NTN_score, NEN_score, NON_score, NFN_score) values (10.0,5.0,0.0,0.0,0.0);
insert into students_score (student_id, NTN_score, NEN_score, NON_score, NFN_score) values (11.0,0.0,6.0,0.0,3.0);
insert into students_score (student_id, NTN_score, NEN_score, NON_score, NFN_score) values (12.0,5.0,0.0,3.0,0.0);
insert into students_score (student_id, NTN_score, NEN_score, NON_score, NFN_score) values (13.0,0.0,0.0,3.0,6.0);
insert into students_score (student_id, NTN_score, NEN_score, NON_score, NFN_score) values (14.0,0.0,6.0,8.0,0.0);
insert into students_score (student_id, NTN_score, NEN_score, NON_score, NFN_score) values (15.0,5.0,0.0,0.0,1.0);
insert into students_score (student_id, NTN_score, NEN_score, NON_score, NFN_score) values (16.0,1.0,0.0,9.0,0.0);
insert into students_score (student_id, NTN_score, NEN_score, NON_score, NFN_score) values (17.0,2.0,0.0,2.0,5.0);
insert into students_score (student_id, NTN_score, NEN_score, NON_score, NFN_score) values (18.0,0.0,0.0,11.0,0.0);
insert into students_score (student_id, NTN_score, NEN_score, NON_score, NFN_score) values (19.0,0.0,0.0,1.0,1.0);
insert into students_score (student_id, NTN_score, NEN_score, NON_score, NFN_score) values (20.0,0.0,2.0,9.0,6.0);
insert into students_score (student_id, NTN_score, NEN_score, NON_score, NFN_score) values (21.0,0.0,4.0,2.0,5.0);
insert into students_score (student_id, NTN_score, NEN_score, NON_score, NFN_score) values (22.0,2.0,0.0,0.0,5.0);
insert into students_score (student_id, NTN_score, NEN_score, NON_score, NFN_score) values (23.0,0.0,0.0,11.0,5.0);
insert into students_score (student_id, NTN_score, NEN_score, NON_score, NFN_score) values (24.0,0.0,1.0,12.0,4.0);
insert into students_score (student_id, NTN_score, NEN_score, NON_score, NFN_score) values (25.0,0.0,7.0,0.0,0.0);
insert into students_score (student_id, NTN_score, NEN_score, NON_score, NFN_score) values (26.0,0.0,0.0,14.0,0.0);
insert into students_score (student_id, NTN_score, NEN_score, NON_score, NFN_score) values (27.0,0.0,0.0,7.0,3.0);
insert into students_score (student_id, NTN_score, NEN_score, NON_score, NFN_score) values (28.0,1.0,0.0,0.0,3.0);
insert into students_score (student_id, NTN_score, NEN_score, NON_score, NFN_score) values (29.0,6.0,0.0,0.0,0.0);
insert into students_score (student_id, NTN_score, NEN_score, NON_score, NFN_score) values (30.0,0.0,0.0,6.0,1.0);
insert into students_score (student_id, NTN_score, NEN_score, NON_score, NFN_score) values (31.0,8.0,0.0,4.0,0.0);
insert into students_score (student_id, NTN_score, NEN_score, NON_score, NFN_score) values (32.0,7.0,0.0,3.0,0.0);
insert into students_score (student_id, NTN_score, NEN_score, NON_score, NFN_score) values (33.0,0.0,0.0,19.0,4.0);
insert into students_score (student_id, NTN_score, NEN_score, NON_score, NFN_score) values (34.0,3.0,0.0,0.0,0.0);
insert into students_score (student_id, NTN_score, NEN_score, NON_score, NFN_score) values (35.0,1.0,0.0,0.0,6.0);
insert into students_score (student_id, NTN_score, NEN_score, NON_score, NFN_score) values (36.0,0.0,0.0,12.0,0.0);
insert into students_score (student_id, NTN_score, NEN_score, NON_score, NFN_score) values (37.0,0.0,0.0,3.0,2.0);
insert into students_score (student_id, NTN_score, NEN_score, NON_score, NFN_score) values (38.0,0.0,0.0,8.0,8.0);
insert into students_score (student_id, NTN_score, NEN_score, NON_score, NFN_score) values (39.0,9.0,0.0,0.0,0.0);
insert into students_score (student_id, NTN_score, NEN_score, NON_score, NFN_score) values (40.0,3.0,0.0,5.0,0.0);
insert into students_score (student_id, NTN_score, NEN_score, NON_score, NFN_score) values (41.0,7.0,0.0,3.0,0.0);
insert into students_score (student_id, NTN_score, NEN_score, NON_score, NFN_score) values (42.0,5.0,0.0,2.0,0.0);
insert into students_score (student_id, NTN_score, NEN_score, NON_score, NFN_score) values (43.0,6.0,0.0,5.0,1.0);
insert into students_score (student_id, NTN_score, NEN_score, NON_score, NFN_score) values (44.0,10.0,0.0,0.0,0.0);
insert into students_score (student_id, NTN_score, NEN_score, NON_score, NFN_score) values (45.0,1.0,0.0,0.0,3.0);
insert into students_score (student_id, NTN_score, NEN_score, NON_score, NFN_score) values (46.0,0.0,7.0,19.0,0.0);
insert into students_score (student_id, NTN_score, NEN_score, NON_score, NFN_score) values (47.0,8.0,0.0,0.0,0.0);
insert into students_score (student_id, NTN_score, NEN_score, NON_score, NFN_score) values (48.0,0.0,0.0,7.0,4.0);
insert into students_score (student_id, NTN_score, NEN_score, NON_score, NFN_score) values (49.0,2.0,0.0,3.0,1.0);
insert into students_score (student_id, NTN_score, NEN_score, NON_score, NFN_score) values (50.0,0.0,0.0,3.0,3.0);
insert into students_score (student_id, NTN_score, NEN_score, NON_score, NFN_score) values (51.0,0.0,0.0,9.0,1.0);
insert into students_score (student_id, NTN_score, NEN_score, NON_score, NFN_score) values (52.0,13.0,0.0,3.0,0.0);
insert into students_score (student_id, NTN_score, NEN_score, NON_score, NFN_score) values (53.0,3.0,0.0,7.0,2.0);
insert into students_score (student_id, NTN_score, NEN_score, NON_score, NFN_score) values (54.0,12.0,0.0,7.0,0.0);
insert into students_score (student_id, NTN_score, NEN_score, NON_score, NFN_score) values (55.0,0.0,0.0,11.0,4.0);
insert into students_score (student_id, NTN_score, NEN_score, NON_score, NFN_score) values (56.0,11.0,0.0,3.0,0.0);
insert into students_score (student_id, NTN_score, NEN_score, NON_score, NFN_score) values (57.0,3.0,0.0,6.0,0.0);
insert into students_score (student_id, NTN_score, NEN_score, NON_score, NFN_score) values (58.0,0.0,0.0,11.0,4.0);
insert into students_score (student_id, NTN_score, NEN_score, NON_score, NFN_score) values (59.0,3.0,0.0,3.0,0.0);
insert into students_score (student_id, NTN_score, NEN_score, NON_score, NFN_score) values (60.0,0.0,0.0,3.0,1.0);
insert into students_score (student_id, NTN_score, NEN_score, NON_score, NFN_score) values (61.0,14.0,0.0,0.0,0.0);
insert into students_score (student_id, NTN_score, NEN_score, NON_score, NFN_score) values (62.0,5.0,0.0,7.0,0.0);
insert into students_score (student_id, NTN_score, NEN_score, NON_score, NFN_score) values (63.0,0.0,1.0,1.0,0.0);
insert into students_score (student_id, NTN_score, NEN_score, NON_score, NFN_score) values (64.0,0.0,0.0,5.0,0.0);
insert into students_score (student_id, NTN_score, NEN_score, NON_score, NFN_score) values (65.0,4.0,0.0,3.0,1.0);
insert into students_score (student_id, NTN_score, NEN_score, NON_score, NFN_score) values (66.0,5.0,0.0,2.0,0.0);
insert into students_score (student_id, NTN_score, NEN_score, NON_score, NFN_score) values (67.0,0.0,0.0,16.0,0.0);
insert into students_score (student_id, NTN_score, NEN_score, NON_score, NFN_score) values (68.0,0.0,9.0,0.0,2.0);
insert into students_score (student_id, NTN_score, NEN_score, NON_score, NFN_score) values (69.0,0.0,0.0,6.0,5.0);
insert into students_score (student_id, NTN_score, NEN_score, NON_score, NFN_score) values (70.0,0.0,0.0,1.0,9.0);
insert into students_score (student_id, NTN_score, NEN_score, NON_score, NFN_score) values (71.0,0.0,0.0,2.0,3.0);
insert into students_score (student_id, NTN_score, NEN_score, NON_score, NFN_score) values (72.0,12.0,10.0,0.0,1.0);
insert into students_score (student_id, NTN_score, NEN_score, NON_score, NFN_score) values (73.0,0.0,8.0,0.0,0.0);
insert into students_score (student_id, NTN_score, NEN_score, NON_score, NFN_score) values (74.0,0.0,0.0,9.0,3.0);
insert into students_score (student_id, NTN_score, NEN_score, NON_score, NFN_score) values (75.0,0.0,0.0,8.0,10.0);
insert into students_score (student_id, NTN_score, NEN_score, NON_score, NFN_score) values (76.0,0.0,0.0,3.0,3.0);
insert into students_score (student_id, NTN_score, NEN_score, NON_score, NFN_score) values (77.0,7.0,0.0,3.0,2.0);
insert into students_score (student_id, NTN_score, NEN_score, NON_score, NFN_score) values (78.0,0.0,0.0,15.0,1.0);
insert into students_score (student_id, NTN_score, NEN_score, NON_score, NFN_score) values (79.0,0.0,0.0,4.0,8.0);
insert into students_score (student_id, NTN_score, NEN_score, NON_score, NFN_score) values (80.0,4.0,0.0,2.0,0.0);
insert into students_score (student_id, NTN_score, NEN_score, NON_score, NFN_score) values (81.0,3.0,0.0,8.0,1.0);
insert into students_score (student_id, NTN_score, NEN_score, NON_score, NFN_score) values (82.0,14.0,0.0,3.0,0.0);
insert into students_score (student_id, NTN_score, NEN_score, NON_score, NFN_score) values (83.0,2.0,0.0,0.0,0.0);
insert into students_score (student_id, NTN_score, NEN_score, NON_score, NFN_score) values (84.0,9.0,0.0,0.0,0.0);
insert into students_score (student_id, NTN_score, NEN_score, NON_score, NFN_score) values (85.0,0.0,10.0,0.0,0.0);
insert into students_score (student_id, NTN_score, NEN_score, NON_score, NFN_score) values (86.0,0.0,0.0,18.0,4.0);
insert into students_score (student_id, NTN_score, NEN_score, NON_score, NFN_score) values (87.0,4.0,1.0,3.0,0.0);
insert into students_score (student_id, NTN_score, NEN_score, NON_score, NFN_score) values (88.0,0,0,0,0);
insert into students_score (student_id, NTN_score, NEN_score, NON_score, NFN_score) values (89.0,0.0,5.0,0.0,4.0);
insert into students_score (student_id, NTN_score, NEN_score, NON_score, NFN_score) values (90.0,2.0,0.0,12.0,7.0);
insert into students_score (student_id, NTN_score, NEN_score, NON_score, NFN_score) values (91.0,0.0,0.0,15.0,8.0);
insert into students_score (student_id, NTN_score, NEN_score, NON_score, NFN_score) values (92.0,0.0,0.0,7.0,4.0);
insert into students_score (student_id, NTN_score, NEN_score, NON_score, NFN_score) values (93.0,0.0,16.0,0.0,0.0);
insert into students_score (student_id, NTN_score, NEN_score, NON_score, NFN_score) values (94.0,0.0,9.0,3.0,0.0);
insert into students_score (student_id, NTN_score, NEN_score, NON_score, NFN_score) values (95.0,9.0,0.0,0.0,0.0);
insert into students_score (student_id, NTN_score, NEN_score, NON_score, NFN_score) values (96.0,0.0,3.0,3.0,14.0);
insert into students_score (student_id, NTN_score, NEN_score, NON_score, NFN_score) values (97.0,1.0,5.0,0.0,0.0);
insert into students_score (student_id, NTN_score, NEN_score, NON_score, NFN_score) values (98.0,5.0,0.0,3.0,0.0);
insert into students_score (student_id, NTN_score, NEN_score, NON_score, NFN_score) values (99.0,0.0,0.0,8.0,0.0);
insert into students_score (student_id, NTN_score, NEN_score, NON_score, NFN_score) values (100.0,2.0,0.0,0.0,0.0);
insert into students_score (student_id, NTN_score, NEN_score, NON_score, NFN_score) values (101.0,0.0,6.0,3.0,5.0);
insert into students_score (student_id, NTN_score, NEN_score, NON_score, NFN_score) values (102.0,0.0,0.0,7.0,0.0);
insert into students_score (student_id, NTN_score, NEN_score, NON_score, NFN_score) values (103.0,0.0,0.0,10.0,8.0);
insert into students_score (student_id, NTN_score, NEN_score, NON_score, NFN_score) values (104.0,2.0,0.0,7.0,6.0);
insert into students_score (student_id, NTN_score, NEN_score, NON_score, NFN_score) values (105.0,1.0,2.0,9.0,2.0);
insert into students_score (student_id, NTN_score, NEN_score, NON_score, NFN_score) values (106.0,4.0,0.0,5.0,0.0);
insert into students_score (student_id, NTN_score, NEN_score, NON_score, NFN_score) values (107.0,0.0,5.0,0.0,7.0);
insert into students_score (student_id, NTN_score, NEN_score, NON_score, NFN_score) values (108.0,0.0,0.0,7.0,15.0);
insert into students_score (student_id, NTN_score, NEN_score, NON_score, NFN_score) values (109.0,0.0,0.0,6.0,6.0);
insert into students_score (student_id, NTN_score, NEN_score, NON_score, NFN_score) values (110.0,3.0,0.0,3.0,0.0);
insert into students_score (student_id, NTN_score, NEN_score, NON_score, NFN_score) values (111.0,0.0,0.0,16.0,5.0);
insert into students_score (student_id, NTN_score, NEN_score, NON_score, NFN_score) values (112.0,0.0,8.0,0.0,0.0);
insert into students_score (student_id, NTN_score, NEN_score, NON_score, NFN_score) values (113.0,0.0,0.0,2.0,3.0);
insert into students_score (student_id, NTN_score, NEN_score, NON_score, NFN_score) values (114.0,3.0,0.0,3.0,5.0);
insert into students_score (student_id, NTN_score, NEN_score, NON_score, NFN_score) values (115.0,2.0,0.0,1.0,0.0);
insert into students_score (student_id, NTN_score, NEN_score, NON_score, NFN_score) values (116.0,0.0,9.0,0.0,0.0);
insert into students_score (student_id, NTN_score, NEN_score, NON_score, NFN_score) values (117.0,7.0,0.0,9.0,5.0);
insert into students_score (student_id, NTN_score, NEN_score, NON_score, NFN_score) values (118.0,0.0,1.0,3.0,2.0);
insert into students_score (student_id, NTN_score, NEN_score, NON_score, NFN_score) values (119.0,9.0,0.0,0.0,2.0);
insert into students_score (student_id, NTN_score, NEN_score, NON_score, NFN_score) values (120.0,3.0,0.0,0.0,17.0);
insert into students_score (student_id, NTN_score, NEN_score, NON_score, NFN_score) values (121.0,0.0,10.0,6.0,2.0);
insert into students_score (student_id, NTN_score, NEN_score, NON_score, NFN_score) values (122.0,0.0,0.0,10.0,6.0);
insert into students_score (student_id, NTN_score, NEN_score, NON_score, NFN_score) values (123.0,9.0,0.0,0.0,0.0);
insert into students_score (student_id, NTN_score, NEN_score, NON_score, NFN_score) values (124.0,0.0,0.0,5.0,3.0);
insert into students_score (student_id, NTN_score, NEN_score, NON_score, NFN_score) values (125.0,0.0,4.0,8.0,2.0);
insert into students_score (student_id, NTN_score, NEN_score, NON_score, NFN_score) values (126.0,3.0,5.0,16.0,0.0);
insert into students_score (student_id, NTN_score, NEN_score, NON_score, NFN_score) values (127.0,0.0,0.0,0.0,7.0);
insert into students_score (student_id, NTN_score, NEN_score, NON_score, NFN_score) values (128.0,0.0,0.0,5.0,8.0);
insert into students_score (student_id, NTN_score, NEN_score, NON_score, NFN_score) values (129.0,0.0,0.0,0.0,6.0);
insert into students_score (student_id, NTN_score, NEN_score, NON_score, NFN_score) values (130.0,0.0,0.0,0.0,0.0);
insert into students_score (student_id, NTN_score, NEN_score, NON_score, NFN_score) values (131.0,0.0,0.0,0.0,15.0);
insert into students_score (student_id, NTN_score, NEN_score, NON_score, NFN_score) values (132.0,0.0,0.0,2.0,6.0);
insert into students_score (student_id, NTN_score, NEN_score, NON_score, NFN_score) values (133.0,0.0,8.0,0.0,0.0);
insert into students_score (student_id, NTN_score, NEN_score, NON_score, NFN_score) values (134.0,0.0,1.0,12.0,9.0);
insert into students_score (student_id, NTN_score, NEN_score, NON_score, NFN_score) values (135.0,0.0,0.0,0.0,5.0);
insert into students_score (student_id, NTN_score, NEN_score, NON_score, NFN_score) values (136.0,0.0,0.0,11.0,3.0);
insert into students_score (student_id, NTN_score, NEN_score, NON_score, NFN_score) values (137.0,5.0,0.0,0.0,0.0);
insert into students_score (student_id, NTN_score, NEN_score, NON_score, NFN_score) values (138.0,0.0,11.0,0.0,0.0);
insert into students_score (student_id, NTN_score, NEN_score, NON_score, NFN_score) values (139.0,6.0,0.0,0.0,0.0);
insert into students_score (student_id, NTN_score, NEN_score, NON_score, NFN_score) values (140.0,0.0,5.0,17.0,5.0);
insert into students_score (student_id, NTN_score, NEN_score, NON_score, NFN_score) values (141.0,1.0,0.0,0.0,0.0);
insert into students_score (student_id, NTN_score, NEN_score, NON_score, NFN_score) values (142.0,5.0,0.0,0.0,0.0);
insert into students_score (student_id, NTN_score, NEN_score, NON_score, NFN_score) values (143.0,5.0,0.0,0.0,0.0);
insert into students_score (student_id, NTN_score, NEN_score, NON_score, NFN_score) values (144.0,0.0,0.0,16.0,0.0);
insert into students_score (student_id, NTN_score, NEN_score, NON_score, NFN_score) values (145.0,10.0,0.0,3.0,0.0);
insert into students_score (student_id, NTN_score, NEN_score, NON_score, NFN_score) values (146.0,0.0,0.0,7.0,0.0);
insert into students_score (student_id, NTN_score, NEN_score, NON_score, NFN_score) values (147.0,0.0,0.0,0.0,6.0);
insert into students_score (student_id, NTN_score, NEN_score, NON_score, NFN_score) values (148.0,7.0,0.0,0.0,0.0);
insert into students_score (student_id, NTN_score, NEN_score, NON_score, NFN_score) values (149.0,0.0,11.0,0.0,0.0);
insert into students_score (student_id, NTN_score, NEN_score, NON_score, NFN_score) values (150.0,0.0,1.0,15.0,7.0);
insert into students_score (student_id, NTN_score, NEN_score, NON_score, NFN_score) values (151.0,4.0,0.0,11.0,0.0);
insert into students_score (student_id, NTN_score, NEN_score, NON_score, NFN_score) values (152.0,0.0,0.0,0.0,0.0);
insert into students_score (student_id, NTN_score, NEN_score, NON_score, NFN_score) values (153.0,3.0,0.0,5.0,0.0);
insert into students_score (student_id, NTN_score, NEN_score, NON_score, NFN_score) values (154.0,3.0,0.0,3.0,0.0);
insert into students_score (student_id, NTN_score, NEN_score, NON_score, NFN_score) values (155.0,0.0,4.0,3.0,0.0);
insert into students_score (student_id, NTN_score, NEN_score, NON_score, NFN_score) values (156.0,16.0,0.0,0.0,0.0);
insert into students_score (student_id, NTN_score, NEN_score, NON_score, NFN_score) values (157.0,7.0,0.0,0.0,0.0);
insert into students_score (student_id, NTN_score, NEN_score, NON_score, NFN_score) values (158.0,2.0,2.0,5.0,4.0);
insert into students_score (student_id, NTN_score, NEN_score, NON_score, NFN_score) values (159.0,0.0,0.0,12.0,4.0);
insert into students_score (student_id, NTN_score, NEN_score, NON_score, NFN_score) values (160.0,0.0,0.0,12.0,5.0);
insert into students_score (student_id, NTN_score, NEN_score, NON_score, NFN_score) values (161.0,4.0,0.0,3.0,2.0);
insert into students_score (student_id, NTN_score, NEN_score, NON_score, NFN_score) values (162.0,10.0,0.0,0.0,0.0);
insert into students_score (student_id, NTN_score, NEN_score, NON_score, NFN_score) values (163.0,0.0,0.0,11.0,6.0);
insert into students_score (student_id, NTN_score, NEN_score, NON_score, NFN_score) values (164.0,0.0,0.0,10.0,2.0);
insert into students_score (student_id, NTN_score, NEN_score, NON_score, NFN_score) values (165.0,0.0,0.0,17.0,0.0);
insert into students_score (student_id, NTN_score, NEN_score, NON_score, NFN_score) values (166.0,5.0,0.0,4.0,1.0);
insert into students_score (student_id, NTN_score, NEN_score, NON_score, NFN_score) values (167.0,2.0,0.0,3.0,0.0);
insert into students_score (student_id, NTN_score, NEN_score, NON_score, NFN_score) values (168.0,0.0,2.0,10.0,2.0);
insert into students_score (student_id, NTN_score, NEN_score, NON_score, NFN_score) values (169.0,1.0,0.0,9.0,2.0);
insert into students_score (student_id, NTN_score, NEN_score, NON_score, NFN_score) values (170.0,2.0,0.0,0.0,9.0);
insert into students_score (student_id, NTN_score, NEN_score, NON_score, NFN_score) values (171.0,0.0,0.0,0.0,3.0);
insert into students_score (student_id, NTN_score, NEN_score, NON_score, NFN_score) values (172.0,0.0,2.0,1.0,4.0);
insert into students_score (student_id, NTN_score, NEN_score, NON_score, NFN_score) values (173.0,2.0,0.0,0.0,0.0);
insert into students_score (student_id, NTN_score, NEN_score, NON_score, NFN_score) values (174.0,0.0,0.0,4.0,4.0);
insert into students_score (student_id, NTN_score, NEN_score, NON_score, NFN_score) values (175.0,3.0,0.0,3.0,2.0);
insert into students_score (student_id, NTN_score, NEN_score, NON_score, NFN_score) values (176.0,4.0,0.0,3.0,3.0);
insert into students_score (student_id, NTN_score, NEN_score, NON_score, NFN_score) values (177.0,0.0,0.0,14.0,3.0);
insert into students_score (student_id, NTN_score, NEN_score, NON_score, NFN_score) values (178.0,6.0,0.0,0.0,0.0);
insert into students_score (student_id, NTN_score, NEN_score, NON_score, NFN_score) values (179.0,9.0,0.0,5.0,0.0);
insert into students_score (student_id, NTN_score, NEN_score, NON_score, NFN_score) values (180.0,0.0,0.0,8.0,4.0);
insert into students_score (student_id, NTN_score, NEN_score, NON_score, NFN_score) values (181.0,0.0,4.0,10.0,0.0);
insert into students_score (student_id, NTN_score, NEN_score, NON_score, NFN_score) values (182.0,0.0,0.0,3.0,10.0);
insert into students_score (student_id, NTN_score, NEN_score, NON_score, NFN_score) values (183.0,0.0,4.0,0.0,2.0);
insert into students_score (student_id, NTN_score, NEN_score, NON_score, NFN_score) values (184.0,0.0,5.0,5.0,0.0);
insert into students_score (student_id, NTN_score, NEN_score, NON_score, NFN_score) values (185.0,0.0,0.0,7.0,2.0);
insert into students_score (student_id, NTN_score, NEN_score, NON_score, NFN_score) values (186.0,0.0,12.0,0.0,1.0);
insert into students_score (student_id, NTN_score, NEN_score, NON_score, NFN_score) values (187.0,2.0,0.0,2.0,0.0);
insert into students_score (student_id, NTN_score, NEN_score, NON_score, NFN_score) values (188.0,0.0,2.0,3.0,2.0);
insert into students_score (student_id, NTN_score, NEN_score, NON_score, NFN_score) values (189.0,1.0,0.0,0.0,3.0);
insert into students_score (student_id, NTN_score, NEN_score, NON_score, NFN_score) values (190.0,0.0,0.0,0.0,13.0);
insert into students_score (student_id, NTN_score, NEN_score, NON_score, NFN_score) values (191.0,3.0,5.0,17.0,0.0);
insert into students_score (student_id, NTN_score, NEN_score, NON_score, NFN_score) values (192.0,0.0,0.0,19.0,5.0);
insert into students_score (student_id, NTN_score, NEN_score, NON_score, NFN_score) values (193.0,7.0,0.0,5.0,1.0);
insert into students_score (student_id, NTN_score, NEN_score, NON_score, NFN_score) values (194.0,8.0,0.0,3.0,0.0);
insert into students_score (student_id, NTN_score, NEN_score, NON_score, NFN_score) values (195.0,3.0,0.0,14.0,0.0);
insert into students_score (student_id, NTN_score, NEN_score, NON_score, NFN_score) values (196.0,0.0,4.0,4.0,2.0);
insert into students_score (student_id, NTN_score, NEN_score, NON_score, NFN_score) values (197.0,0.0,3.0,0.0,5.0);
insert into students_score (student_id, NTN_score, NEN_score, NON_score, NFN_score) values (198.0,6.0,2.0,0.0,0.0);
insert into students_score (student_id, NTN_score, NEN_score, NON_score, NFN_score) values (199.0,2.0,0.0,0.0,0.0);
insert into students_score (student_id, NTN_score, NEN_score, NON_score, NFN_score) values (200.0,9.0,2.0,3.0,0.0);
insert into students_score (student_id, NTN_score, NEN_score, NON_score, NFN_score) values (201.0,0.0,0.0,0.0,0.0);
insert into students_score (student_id, NTN_score, NEN_score, NON_score, NFN_score) values (202.0,0.0,0.0,15.0,1.0);
insert into students_score (student_id, NTN_score, NEN_score, NON_score, NFN_score) values (203.0,6.0,0.0,3.0,0.0);